version: "3.9"
services:
  db:
    image: postgres:14
    container_name: my_hotwire_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: my_hotwire_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: secret
      RAILS_ENV: development
    depends_on:
      - db

volumes:
  db_data: